{
 "title": "nestjs-otel Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.025\",status=~\"^2..$\", exported_job=\"nestjs-example\"}[1m]))\n+\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.1\",status=~\"^2..$\", exported_job=\"nestjs-example\"}[1m]))\n) / 2 / sum(rate(http_request_duration_seconds_count{exported_job=\"nestjs-example\"}[1m]))"
    }
   ]
  },
  {
   "title": "Apdex Score: target 25ms, tolerated: 100ms",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  sum(irate(http_request_duration_seconds_bucket{le=\"0.025\",status=~\"^2..$\", exported_job=\"nestjs-example\"}[1m]))\n+\n  (sum(irate(http_request_duration_seconds_bucket{le=\"0.1\",status=~\"^2..$\", exported_job=\"nestjs-example\"}[1m]))/2)\n) / sum(irate(http_request_duration_seconds_count{exported_job=\"nestjs-example\"}[1m]))",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Requests in Processing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_active_requests_total{exported_job=\"nestjs-example\"})"
    }
   ]
  },
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{exported_job=\"nestjs-example\"}",
     "legendFormat": "Process Memory - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{exported_job=\"nestjs-example\"}",
     "legendFormat": "Heap Total - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{exported_job=\"nestjs-example\"}",
     "legendFormat": "Heap Used - {{pod}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{exported_job=\"nestjs-example\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{exported_job=\"nestjs-example\"}[2m]) * 100",
     "legendFormat": "User CPU"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{exported_job=\"nestjs-example\"}[2m]) * 100",
     "legendFormat": "Sys CPU"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{exported_job=\"nestjs-example\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{exported_job=\"nestjs-example\"}",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "nodejs_active_requests_total{exported_job=\"nestjs-example\"}",
     "legendFormat": "Active Request"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{exported_job=\"nestjs-example\"}",
     "legendFormat": "Heap Total - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{exported_job=\"nestjs-example\"}",
     "legendFormat": "Heap Used - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{exported_job=\"nestjs-example\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  },
  { "title": "Http Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Historic P90 response time by endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{exported_job=\"nestjs-example\"}[1m])) by (le,method,path)) * 1000",
     "legendFormat": "{{method}}#{{path}}"
    }
   ]
  },
  {
   "title": "Historic P50 response time by endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{exported_job=\"nestjs-example\"}[1m])) by (le,method,path)) * 1000",
     "legendFormat": "{{method}}#{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Responses by status code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status,method) (increase(http_request_duration_seconds_count{exported_job=\"nestjs-example\"}[$__rate_interval]))",
     "legendFormat": "{{method}}: {{status}} status"
    }
   ]
  },
  {
   "title": "Top HTTP paths used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (increase(http_request_duration_seconds_count{exported_job=\"nestjs-example\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Throughput by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{exported_job=\"nestjs-example\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{exported_job=\"nestjs-example\"}[1m])) * 10\n/\nsum(rate(http_request_duration_seconds_count{exported_job=\"nestjs-example\"}[1m])) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Probe Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status=~\"[45]..\", exported_job=\"nestjs-example\"}[1m])) by (job) / sum(rate(http_request_duration_seconds_count{exported_job=\"nestjs-example\"}[1m])) by (job)",
     "legendFormat": "error ratio"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{exported_job=\"nestjs-example\"}[1m])) by (job)",
     "legendFormat": "total requests rate"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status=\"500\", exported_job=\"nestjs-example\"}[1m])) by (job)",
     "legendFormat": "error responses rate"
    }
   ]
  }
 ]
}