on:
  push:
    branches:
      - main
name: release-please
permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: GoogleCloudPlatform/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - if: ${{ steps.release.outputs.release_created }}
        run: npm install -g npm
      - if: ${{ steps.release.outputs.release_created }}
        run: npm ci --legacy-peer-deps
      - if: ${{ steps.release.outputs.release_created }}
        run: npm run build
      - id: publish
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
